### ISSUE TITLE
rescaling gomwuPlot

### ISSUE THREAD

**Issue by yaaminiv** [z0on/GO_MWU#14]
Is there any way to rescale a gomwuPlot without with R code instead of creating a plotting window with `quartz`? I'm finding the `quartz` method isn't working on my computer.

**Comment by z0on** [comment]
To be honest I am not a good enough programmer to code this...
you are correct, quartz would not work on Windows R or in Rstudio. But you
can manually rescale the zoomed-out plot window (Rstudio) and save the
image. To preserve full resolution, redirect the plot to pdf and try
different plot sizes - height and width options to the pdf() function -
until it looks right. Silly, but it works :)
