### ISSUE TITLE
Error running gomwuStats

### ISSUE THREAD

**Issue by yaaminiv** [z0on/GO_MWU#3]
I am running my modified version of a GO-MWU script (found [here](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/nonZostera-GO_MWU.R)), using [this annotation file](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/2019-07-11-nonZostera-GO-Annotations-Table.tab) and [this table of significance measures](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/2019-07-11-nonZostera-Table-of-Significance-Measures.csv). I keep encountering the following error when running `gomwuStats`:

<img width="833" alt="Screen Shot 2019-07-12 at 12 10 47 AM" src="https://user-images.githubusercontent.com/22335838/61109451-c4998f80-a439-11e9-8926-9ce320c50e99.png">

<img width="834" alt="Screen Shot 2019-07-11 at 11 42 57 PM" src="https://user-images.githubusercontent.com/22335838/61109453-c6635300-a439-11e9-9b5d-6a05ff7a4ef0.png">

I ran a [similar GO-MWU analysis](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/Zostera-GO_MWU.R) successfully using an [this annotation table](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/2019-07-11-Zostera-GO-Annotations-Table.tab) and [this significance table](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/2019-07-11-Zostera-Table-of-Significance-Measures.csv), so I'm unsure why I'm getting this error now. Both sets of input files were created with [this script](https://github.com/eimd-2019/project-EWD-transcriptomics/blob/master/analyses/GO-MWU/2019-07-11-Gene-Enrichment-with-GO-MWU.Rmd).

Is there any sort of code modification I need to make in order to run the script?

**Comment by z0on** [comment]
Hi Yaamini - thanks for trying out my method!

This error usually pops up when some formatting of the input file(s) is wrong - open you “measures” file in a plain text editor to confirm that “measures” is indeed a comma-separated table with no additional things, and “annotation” is tab-delimited, with multiple GO terms separated by just semicolon (no spaces!)

One thing though - you seem to have included only “significant" genes in the measures table. This is wrong - you should list all genes for which the testing was done, significant as well as non-significant ones. This is a particular strength of GO_MWU - to does not require any prior statistical testing or imposing of arbitrary “significance cutoffs” instead it looks at the whole list of genes ranked by response strength. You can even use raw log-fold-changes as a measure to rank them.

Misha

**Comment by yaaminiv** [comment]
> This error usually pops up when some formatting of the input file(s) is wrong - open you “measures” file in a plain text editor to confirm that “measures” is indeed a comma-separated table with no additional things, and “annotation” is tab-delimited, with multiple GO terms separated by just semicolon (no spaces!)

I deleted my original files and used the same code I had to recreate them. Not sure what the difference was this time, but it worked!

> you should list all genes for which the testing was done, significant as well as non-significant ones

Re-ran the code using all genes. Thank you for the clarification!
