### ISSUE TITLE
gomwu_b: cannot create output dissim0_BP_

### ISSUE THREAD

**Issue by shellytrigg** [z0on/GO_MWU#4]
Hello,

I continue to get the following error thrown by the gomwu_b.pl script and I'm not sure what's going on. Any advice is appreciated, thanks! -Shelly

gomwuStats(input, goDatabase, goAnnotations, goDivision,
+ 	perlPath="perl", # replace with full path to perl executable if it is not in your system's PATH already
+ 	largest=0.1,  # a GO category will not be considered if it contains more than this fraction of the total number of genes
+ 	smallest=5,   # a GO category should contain at least this many genes to be considered
+ 	clusterCutHeight=0.25) # threshold for merging similar
gomwu_b: cannot create output dissim0_BP_/Users/Shelly/Documents/GitHub/OysterSeedProject/analysis/UniprotAnnotations_NetworkAnalysis/ASCA_logNSAFs_FunctionalAnalysis/silo23_all_pro_GO.tab

**Comment by z0on** [comment]
Hi Shelly - too easy! try putting your input file into the directory where all the script files are and run it using the input file name without path (i.e, just “silo23_all_pro_GO.tab”)
Mish

**Comment by shellytrigg** [comment]
Hey Mish, all my input files are in the directory where all the script files are. I'll try removing the path and see if it runs. I also found some formatting discrepancies in my input file (it included column names and there were "; " separating each GO term. Hopefully it works after these changes. Thanks for your quick response!

**Comment by z0on** [comment]
that error definitely was because the input filename included path, but hey, there always could be other errors as well! :) please don’t hesitate to ask

**Comment by shellytrigg** [comment]
it worked! thanks so much!
